### ISSUE TITLE
Implement predict function

### ISSUE THREAD

**Issue by loelschlaeger** [loelschlaeger/fHMM#26]
Use model results to forecast the market.

**Comment by mackancurtaincheeks** [comment]
![lenn2](https://user-images.githubusercontent.com/47204968/116206554-36da8180-a73f-11eb-9315-94834079d68c.JPG)

The 'decoded time series' picture submitted above do show predicting logreturns after the time we trained the model on or am I wrong about that?

**Comment by loelschlaeger** [comment]
The package does not perform prediction (yet). The label "2020" marks the date "2020-01-01".

**Comment by mackancurtaincheeks** [comment]
> The package does not perform prediction (yet). The label "2020" marks the date "2020-01-01".

Oh.. Then I totally misunderstood the purpose of this package, darn it. That is what you get for not reading everything.

Thanks alot for all the replies and patience - I will try my luck somewhere else and comeback in the future when the 'forecast' function is added!

**Comment by mackancurtaincheeks** [comment]
With an ordinary HMM it would be possiblebto generate outcomes by just using the Viterbi sequence and just sampler the gaussian emission models. How would you go about trying to do the same with this model?

**Comment by thebadguyfromstarwars** [comment]
> With an ordinary HMM it would be possiblebto generate outcomes by just using the Viterbi sequence and just sampler the gaussian emission models. How would you go about trying to do the same with this model?

I am having this exact problem. I feel like you should be able to extrapolate from the fitted model and just by some easy functions be able to do predictions. As you said - it's quite easy with a ordinary HMM, you just continiously use the trasition matrix and then sample the different emission models. Maybe we could do something together?

**Comment by loelschlaeger** [comment]
> I am having this exact problem. I feel like you should be able to extrapolate from the fitted model and just by some easy functions be able to do predictions. As you said - it's quite easy with a ordinary HMM, you just continiously use the trasition matrix and then sample the different emission models. Maybe we could do something together?

This is definitely a goal for the next package version of fHMM. If you want to contribute, we are happy if you fork the package and make a pull request.
