### ISSUE TITLE
Warnings when using other datasets

### ISSUE THREAD

**Issue by mackancurtaincheeks** [loelschlaeger/fHMM#40]
download_data("dax", "^GDAXI", path=".")

download_data("hk", "HEN3.DE", path=".")

horizon: 2020-01-02 to 2021-03-01

Warnings: 
1. possibly unidentified states (C.6)
2. events ignored (V.2)

**Comment by loelschlaeger** [comment]
That is no bug. Please use `fHMM::exception(<code>)` for information.
