### ISSUE TITLE
Access the predicted values in a list/array

### ISSUE THREAD

**Issue by mackancurtaincheeks** [loelschlaeger/fHMM#43]
I'm doing an analysis of our predictions and I would like to access the output in a list/array so I could run MAPE, MSE and some other indicators. I can't seem to find it - where is it?

**Comment by loelschlaeger** [comment]
fHMM saves .rds-files of the model results, see https://github.com/loelschlaeger/fHMM#outputs

**Comment by mackancurtaincheeks** [comment]
Hello Lennart! I know, that's why I was asking - I don't find anything remotely similar to 'prediced data'. I find the raw data and log returns and other control . Would you like to point me in the right direction, please?

**Comment by loelschlaeger** [comment]
Prediction is not yet implemented (see #26). Are you looking for the decoded states? Then, see `decoding.rds`.

**Comment by mackancurtaincheeks** [comment]
Ah, okay.. i thought the logreturns was calculated through the actual predicted price. I will have to rethink the angle of the project a bit.
