### ISSUE TITLE
Is there a built-in function to graph the simulated data?

### ISSUE THREAD

**Issue by thebadguyfromstarwars** [loelschlaeger/fHMM#45]
First of all - I love the package! I struggled with some not-so-userfriendly packages in the past, but this is really something else!

To my question - is there existing funtion in the package to visualize/plot only the simulated data but with the same structure, visualizing the state scales underneath?

If not - is the simulated data bundled together with the data I fitted the model on in the **data.rds** file?

![lenn](https://user-images.githubusercontent.com/83267247/116192964-e9eeaf00-a72e-11eb-902b-77900095ee2a.JPG)

In the picture above, **logReturns** and **dataRaw** with 2714 elements. I only modelled a year, so this got to be all of the data, right? So I only need to fetch he last 365 elements and then I'm fine?

I do hope I was clear enough. If there are any confusion, just leave a quick comment and I will try to explain further.

Thanks in advance,

Carlos

**Comment by loelschlaeger** [comment]
Thanks! 

Please clarify your question: What do you mean by "only the simulated data but with the same structure, visualizing the state scales underneath"? Please refer to https://github.com/loelschlaeger/fHMM/blob/master/models/HMM_2_sim_gamma/decoded_time_series.pdf, where you see a visualization of a simulated, decoded time series.

If you let the code simulate data for you, the simulated data is saved in `data.rds`.

**Comment by thebadguyfromstarwars** [comment]
Sorry for being obtruse!

I'm refering to this graph above

https://github.com/loelschlaeger/fHMM/blob/master/models/HMM_3_DAX/decoded_time_series.pdf

where you can see the fitted model with the different states shown underneath. I would like to do this kind of visualization but with the forecasted data. Then it would be possible to show how the model is working in regards to how the different states make up the whole model.

Yes, I know. I got the logReturns and the dataRaw - one holidng the logreturns and one the price values. But I want to access the prices/logreturns from t+1, do I only have to used indexes to get the last dates then?

**Comment by thebadguyfromstarwars** [comment]
Sorry, I now saw you have already responded to a similiar question.

**Comment by loelschlaeger** [comment]
Forecasting is not possible with the current package version, however, it is planned as a future extension, see #26 .
