### ISSUE TITLE
Error in fit_hmm(controls, events) : Id invalid. (S.1)

### ISSUE THREAD

**Issue by roywwei** [loelschlaeger/fHMM#47]
Run github instance, error reported

**Comment by loelschlaeger** [comment]
Thanks. Which model did you specify? You can run `fHMM::exception("S.1")` to get suggestions for debugging. In this case, it seems that a model with the same id already exists in your path. Try running `fit_hmm(controls=list("id"="new"))`.

**Comment by roywwei** [comment]
> c

Thank you for your prompt reply and problem solved.
