### ISSUE TITLE
Error in check_controls(controls): File './data/x.csv' not found.

### ISSUE THREAD

**Issue by filippocuscito29** [loelschlaeger/fHMM#51]
Hi, 

I am trying to fit an hhmm on copper data, however, after 

> fit_hmm(controls, events)

the following error pops up:

Error in check_controls(controls): File './data/x.csv' not found.

Thank you in advance for the support.

**Comment by loelschlaeger** [comment]
How did you specify your controls? Please provide a minimal reproducible example.

**Comment by filippocuscito29** [comment]
Here is the code:

>download_data(name = "Copper", symbol = "HG=F", path = ".")

>controls = list(path = ".", id = "HHMM_3_2_COPPER_t", model = "hhmm",
states = c(3,2), sdds = c("t", "t"), horizon = c(30, "w"), data =
list("source" = c("coarse", "fine"), "column" = c("Close", "Close"),
"cs_transform" = function(x) (tail(x,1)-head(x,1))/head(x,1), "log_returns"
= c(FALSE, TRUE), "truncate" = c("2000-01-01", NA)), fit = list("runs" =
100))


> events = list(dates = c("2008-07-01"), names = ("73 days to Lehman
crash"))


> fit_hmm(controls, events)


Looking forward to hearing from you.

I really don’t understand what I am getting wrong.


Filippo


Il giorno gio 12 ago 2021 alle 23:03 Lennart Oelschläger <
***@***.***> ha scritto:

**Comment by filippocuscito29** [comment]
Here is the code:

>download_data(name = "Copper", symbol = "HG=F", path = ".") 

>controls = list(path = ".", id = "HHMM_3_2_COPPER_t", model = "hhmm", states = c(3,2), sdds = c("t", "t"), horizon = c(30, "w"), data = list("source" = c("coarse", "fine"), "column" = c("Close", "Close"), "cs_transform" = function(x) (tail(x,1)-head(x,1))/head(x,1), "log_returns" = c(FALSE, TRUE), "truncate" = c("2000-01-01", NA)), fit = list("runs" = 100)) 

> events = list(dates = c("2008-07-01"), names = ("73 days to Lehman crash")) 

> fit_hmm(controls, events) 

Looking forward to hearing from you. 
I really do not understand what I am getting wrong.

**Comment by loelschlaeger** [comment]
You misspecified `controls$data$source`.  You need the name of the .csv file with your data there. The following worked for me:
```r
install.packages("fHMM")
library("fHMM")
download_data(name = "Copper", symbol = "HG=F", path = ".")
controls = list(path = ".", 
                id = "HHMM_3_2_COPPER_t", 
                model = "hhmm", states = c(3,2), 
                sdds = c("t", "t"), 
                horizon = c(30, "w"), 
                data = list("source" = c("copper.csv", "copper.csv"), 
                            "column" = c("Close", "Close"), 
                            "cs_transform" = function(x) (tail(x,1)-head(x,1))/head(x,1), 
                            "log_returns" = c(FALSE, TRUE), 
                            "truncate" = c("2000-01-01", NA)), 
                fit = list("runs" = 100))
events = list(dates = c("2008-07-01"), names = ("73 days to Lehman crash"))
fit_hmm(controls, events)
```
