### ISSUE TITLE
Falsche state-dependent distribution bei 3 States

### ISSUE THREAD

**Issue by RouvenM** [loelschlaeger/fHMM#65]
Beim Durchlaufen dieses Codes:

simulated HMM -----------------------------------------------------------
seed = 1
controls = list(
states = 3,
sdds = "gamma",
horizon = 500,
fit = list("runs" = 100)
)
controls %<>% set_controls
data = prepare_data(controls, seed = seed)
data %>% summary
data %>% plot
model = fit_model(data, ncluster = 1, seed = seed) %>%
decode_states %>%
compute_residuals
summary(model)
model %<>% reorder_states(state_order = 1:3)
compare(model)
model %>% plot("ll")
model %>% plot("sdds")

![image](https://user-images.githubusercontent.com/78567974/145246085-eeb83b61-a292-469f-9058-bccbaa7062cb.png)

wird der 3. Status leider nicht richtig erkannt. Ich habe dasselbe auch mit 1000 Runs einmal ausgeführt, geändert hat sich am Ergebnis allerdings nichts.

**Comment by loelschlaeger** [comment]
Ich denke das ist kein Bug. Eher geben die Daten nicht mehr her. Ich habe das gleiche Modell mit `horizon = 5000` geschätzt (also 10mal mehr Daten). Die SDDs werden jetzt besser geschätzt (s.u.). Aber die wahren SDDs vom gelben und vom roten Zustand sind sich einfach zu ähnlich, die sind schwer zu schätzen. In deinem Fall modelliert der gelbe Zustand wahrscheinlich viel vom roten Zustand mit und der rote Zustand erfasst die Ausreißer. 

![image](https://user-images.githubusercontent.com/57176318/145250315-4b718247-b6ec-41b9-9b6c-47d59199753b.png)
