### ISSUE TITLE
How to obtain the probability transition matrix and emission matrix of hidden states?

### ISSUE THREAD

**Issue by zoushucai** [loelschlaeger/fHMM#82]
Hello, I am using this software package to fit an HMM. I only have one column of data and I would like to obtain the transition probability matrix and emission matrix for the hidden state sequence. Can you please advise me on how to do this?

**Comment by zoushucai** [comment]
I think I found the answer. I used to extract it directly using coef. I think the 'gamma' in it is the implicit transition matrix, but I didn't notice it at the time.,

**Comment by loelschlaeger** [comment]
Hi @zoushucai ! 

Yes, you can use the `coef()` method, it returns all the estimated parameters. 

There is another way, which I will illustrate using (a reduced version of) the example in the README:

```r
library("fHMM")
dax <- download_data(symbol = "^GDAXI", file = NULL, verbose = FALSE)
controls <- list(
  states = 3,
  sdds   = "t",
  data   = list(file        = dax,
                date_column = "Date",
                data_column = "Close",
                logreturns  = TRUE,
                from        = "2000-01-01",
                to          = "2010-12-31"),
  fit    = list(runs        = 10)
)
controls <- set_controls(controls)
data <- prepare_data(controls)
model <- fit_model(data)
model <- decode_states(model)
model <- compute_residuals(model)
```

After executing these lines, you can inspect the `model` object and find that it contains the element `estimate`, which is a `parUncon` object. These are unconstrained parameter estimates. To constrain them and so to get the actual parameter estimates, you can use the non-exported function `fHMM:::parUncon2par()` as follows:

```r
parameters <- fHMM:::parUncon2par(model$estimate, controls)
```

Now, `parameters` is an `fHMM_parameters` object, which is a `list` that contains the estimated parameters, for example, the element `Gamma`, which is the transition probability matrix:

```r
parameters$Gamma
```

This is not very convenient, we will provide easier access in the next package version. Thanks a lot for your feedback!

For the emission probabilities, please have a look at the `predict()` method:

```r
predict(model)
```

**Comment by zoushucai** [comment]
thank you @loelschlaeger

**Comment by zoushucai** [comment]
> Hi @zoushucai ! 你好，0#！你好，0#！  你好，0#！
> 
> Yes, you can use the `coef()` method, it returns all the estimated parameters.是的，您可以使用 `coef()` 方法，它返回所有估计的参数。是的，您可以使用 `coef()` 方法，它返回所有估计的参数。
> 
> There is another way, which I will illustrate using (a reduced version of) the example in the README:还有另一种方法，我将使用README中的示例（简化版本）进行说明：还有另一种方法，我将使用README中的示例（简化版本）进行说明： 还有另一种方法，我将使用README中的示例（简化版本）进行说明： 
> 
> ```r
> library("fHMM")
> dax <- download_data(symbol = "^GDAXI", file = NULL, verbose = FALSE)
> controls <- list(
>   states = 3,
>   sdds   = "t",
>   data   = list(file        = dax,
>                 date_column = "Date",
>                 data_column = "Close",
>                 logreturns  = TRUE,
>                 from        = "2000-01-01",
>                 to          = "2010-12-31"),
>   fit    = list(runs        = 10)
> )
> controls <- set_controls(controls)
> data <- prepare_data(controls)
> model <- fit_model(data)
> model <- decode_states(model)
> model <- compute_residuals(model)
> ```
> 
> After executing these lines, you can inspect the `model` object and find that it contains the element `estimate`, which is a `parUncon` object. These are unconstrained parameter estimates. To constrain them and so to get the actual parameter estimates, you can use the non-exported function `fHMM:::parUncon2par()` as follows:在执行了这些行之后，您可以检查 `model` 对象，并发现它包含元素 `estimate` ，这是一个 `parUncon` 对象。这些是无约束参数估计值。为了约束它们并获得实际的参数估计值，您可以使用非导出函数 `fHMM:::parUncon2par()` ，如下所示：在执行了这些行之后，您可以检查 `model` 对象，并发现它包含元素 `estimate` ，这是一个 `parUncon` 对象。这些是无约束参数估计值。为了约束它们并获得实际的参数估计值，您可以使用非导出函数 `fHMM:::parUncon2par()` ，如下所示：
> 
> ```r
> parameters <- fHMM:::parUncon2par(model$estimate, controls)
> ```
> 
> Now, `parameters` is an `fHMM_parameters` object, which is a `list` that contains the estimated parameters, for example, the element `Gamma`, which is the transition probability matrix:现在， `parameters` 是 `fHMM_parameters` 对象，其是包含估计参数的 `list` ，例如元素 `Gamma` ，其是转移概率矩阵：现在， `parameters` 是 `fHMM_parameters` 对象，其是包含估计参数的 `list` ，例如元素 `Gamma` ，其是转移概率矩阵：
> 
> ```r
> parameters$Gamma
> ```
> 
> This is not very convenient, we will provide easier access in the next package version. Thanks a lot for your feedback!这不是很方便，我们将在下一个包版本中提供更容易的访问。感谢您的评分这不是很方便，我们将在下一个包版本中提供更容易的访问。感谢您的评分 这不是很方便，我们将在下一个包版本中提供更容易的访问。感谢您的评分 
> 
> For the emission probabilities, please have a look at the `predict()` method:关于发射概率，请看 `predict()` 方法：关于发射概率，请看 `predict()` 方法：
> 
> ```r
> predict(model)
> ```


I found that the transition probability matrix extracted using `coef` is different from the transition probability matrix extracted using `fHMM:: parUncon2Par()`. Can you help me explain? I don't quite understand
