### ISSUE TITLE
feeback / ideas for future improvments

### ISSUE THREAD

**Issue by ashraf-01** [loelschlaeger/fHMM#89]
You are missing a functionality? Thanks for telling! Please briefly describe below what and where.
hi thanks for the effort loel

but why you did not add an additional feature to show improvements using hierarchical version of the HMM over the standard plain simple version of HMM ? and secondly is there a way to estimate the false positive rate of let say assigning a variable to a state like say returns to specific state / cluster ? 
lastly is there a way to cluster using multiple variables not just one , let say interest rates and volatility of the underlying ....etc 

your input is highly appreciated

**Comment by loelschlaeger** [comment]
Hi @ashraf-01, thanks a lot for your suggestions, they are all very valuable for us.

- `but why you did not add an additional feature to show improvements using hierarchical version of the HMM over the standard plain simple version of HMM ?` This falls into the topic of model selection. Users of the package can estimate both types of models and compare the results. The package offers the `compare_models()` function to compare models using information criteria (see https://loelschlaeger.de/fHMM/articles/v07_model_selection.html), but we plan to extend here. Is there any particular way you would like to measure improvements?
- `and secondly is there a way to estimate the false positive rate of let say assigning a variable to a state like say returns to specific state / cluster ?` Yes, you can always simulate data from an estimated (H)HMM and compare the true versus the decoded states. This gives you an idea about the performance for empirical data. In the next package version, we will be more explicit about this.
- `lastly is there a way to cluster using multiple variables not just one , let say interest rates and volatility of the underlying ....etc` What exactly do you mean by "cluster"? Please specify. If you mean modelling a multivariate time series, this is not implemented currently, but maybe will be in the future. 

Best regards,
Lennart

**Comment by ashraf-01** [comment]
HI Loel

here is a reference to have a look at(https://www.latentclassanalysis.com/wp-content/uploads/2021/04/12-119-1.pdf) , then I would like to know from you do you consider your DGM (data-generating model) behind HHMM as diffuse type or sparse type ? according to the response you give , I can check then which IC criteria should be used , secondly du eto the nature of the things that I want to do with such functions within the package , I prefer to use something- especially for communication purposes- as simple as false positive rate , to judge among n models , for example how many returns of specific type of transactions (risk premium sources as they call it in finance liturature) belong to which state , or in cancer applications , which type of cancer belong to which type of combined risk profile of a patient , so I have to be able at least - as in clustering algorithms within ML  - to see that certain data points which are driven by some common latent factors tend to group together , otherwise the model is not able to do the right grouping , are you getting my point ?!
I believe using the false positive rate would be very robust criteria to lean on in such case

Your input is highly appreciated

Justice is in peace and peace is in Justice

@ashraf

Kind Regards
Mit freundlichen Grüße
Cordialement
أطيب التحيات
________________________________

**Comment by loelschlaeger** [comment]
Thanks for the reference, for HMMs we recommend AIC or BIC model selection criteria in combination with domain expertise and model checking. 

Regarding false positive rate, this can only be provided for simulated data. In empirical data, the latent states (like current market volatility regime) is only observed through realizations of the stock. However, one option can always be to simulate an HMM based on estimates from the empirical analysis. For simulated HMMs, the true latent states are known, and false positive rates can be calculated. This is already implemented in the `predict()` method.
